export enum UIConditionType {
  visible = 'VISIBLE',
  exist = 'EXIST',
  hidden = 'HIDDEN',
  appear = 'APPEAR',
  disappear = 'DISAPPEAR',
  readonly = 'READONLY',
  empty = 'EMPTY',
  image = 'IMAGE',
  focused = 'FOCUSED',
  enabled = 'ENABLED',
  disabled = 'DISABLED',
  selected = 'SELECTED',
  checked = 'CHECKED',
}
